# main menu
[[main]]
name = "Tractometer"
URL = "tractometer/"
weight = 1
hasChildren = true

    [[main]]
    parent = "Tractometer"
    name = "Home"
    identifier = "tractometer_home"
    URL = ""
    weight = 1

    [[main]]
    parent = "Tractometer"
    name = "Bundle segmentation"
    identifier = "bundle_segmentation"
    URL = "tractometer/bundle_segmentation"
    weight = 2

    [[main]]
    parent = "Tractometer"
    name = "The metrics"
    URL = "tractometer/the_metrics"
    weight = 3

    [[main]]
    parent = "Tractometer"
    name = "References"
    identifier = "tractometer_references"
    URL = "tractometer/references"
    weight = 4

    [[main]]
    parent = "Tractometer"
    name = "Contact and support"
    URL = "tractometer/contact_and_support"
    weight = 5

[[main]]
name = "Fibercup"
weight = 2
hasChildren = true

    [[main]]
    parent = "Fibercup"
    name = "Home"
    identifier = "fibercup_home"
    URL = "fibercup/home"
    weight = 1

    [[main]]
    parent = "Fibercup"
    name = "Data"
    identifier = "fibercup_data"
    URL = "fibercup/data"
    weight = 2

    [[main]]
      parent = "Fibercup"
      name = "References"
      identifier = "fibercup_references"
      URL = "fibercup/references"
      weight = 3

[[main]]
name = "ISMRM 2015 Challenge"
weight = 3
hasChildren = true

    [[main]]
      parent = "ISMRM 2015 Challenge"
      name = "Home"
      identifier = "imsmrm_home"
      URL = "ismrm2015/home"
      weight = 1

    [[main]]
      parent = "ISMRM 2015 Challenge"
      name = "DWI data"
      identifier = "ismrm_data_dwi"
      URL = "ismrm2015/dwi_data"
      weight = 2

    [[main]]
      parent = "ISMRM 2015 Challenge"
      name = "Tractography data"
      identifier = "ismrm_data_gt"
      URL = "ismrm2015/tractography_data"
      weight = 3

    [[main]]
      parent = "ISMRM 2015 Challenge"
      name = "An example of processed data"
      identifier = "ismrm_data_example"
      URL = "ismrm2015/processed_data"
      weight = 4

    [[main]]
      parent = "ISMRM 2015 Challenge"
      name = "Results"
      identifier = "ismrm_results"
      URL = "ismrm2015/results"
      weight = 5

    [[main]]
      parent = "ISMRM 2015 Challenge"
      name = "Tools"
      identifier = "ismrm_tools"
      URL = "ismrm2015/tools"
      weight = 6

    [[main]]
      parent = "ISMRM 2015 Challenge"
      name = "References"
      identifier = "ismrm_references"
      URL = "ismrm2015/references"
      weight = 7

[[main]]
name = "Gallery"
url = "gallery/"
weight = 4
